#!/usr/bin/env bash

set -e

links=(
	"dwm/config.h:~/git/suckless/dwm/config.h"
	"fish/config.fish:~/.config/fish/config.fish"
	"fish/fish_variables:~/.config/fish/fish_variables"
	"git/.gitconfig:~/.gitconfig"
	"gtk-3.0:~/.config/gtk-3.0"
	"nvim:~/.config/nvim"
	"scripts:~/scripts"
	"st/config.h:~/git/github/riridotdev/st/config.h"
	"x11/.xinitrc:~/.xinitrc"
	"systemd/keyboard-remapper.service:/etc/systemd/system/keyboard-remapper.service"
)

cd "$(dirname "$(realpath "$0")")"

for link in "${links[@]}"; do
	link_parts=(${link/:/ })

	link_parts[0]=$(realpath "${link_parts[0]}")
	link_parts[1]="${link_parts[1]/\~/$HOME}"

	target_dirname=$(dirname "${link_parts[1]}")
	if [ ! -d "${target_dirname}" ]; then
		mkdir -p "${target_dirname}"
	fi

	if [ -L "${link_parts[1]}" ]; then
		if [ "$(readlink "${link_parts[1]}")" = "${link_parts[0]}" ]; then
			echo "${link_parts[1]} -> ${link_parts[0]} already exists"
			continue
		fi

		echo "conflicting link found at ${link_parts[1]}" >&2
		exit 1
	fi

	if [ -e "${link_parts[1]}" ]; then
		echo "conflicting file found at ${link_parts[1]}" >&2
		exit 1
	fi

	echo "linking ${link_parts[1]} to ${link_parts[0]}"
	sudo -E ln -sn "${link_parts[0]}" "${link_parts[1]}"
done
