#!/usr/bin/env bash

set -e

device_name=$(lsblk -l -o NAME,LABEL | grep '\sriri' | cut -f1 -d' ')

if [ -z "${device_name}" ]; then
    echo "Error: no device found"
    exit 1
fi

if [ ! -e /dev/mapper/riri ]; then
    sudo cryptsetup open /dev/${device_name} riri
fi

if ! mount | grep /dev/mapper/riri &>/dev/null; then
    sudo mount --mkdir /dev/mapper/riri ~/mount/riri
fi
